#!/bin/bash
# mise description="View remote codeberg repository"

HOSTNAME=$(hostname)
CODEBERG_URL="https://codeberg.org/mimikun/wezterm-new-config"

if [[ "$HOSTNAME" = "azusa" ]]; then
    open "$CODEBERG_URL"
else
    wsl-open "$CODEBERG_URL"
fi

# vim:ft=bash
